### ISSUE TITLE
What is a NaN for an Integer Type?

### ISSUE THREAD

**Issue by JeffreySarnoff** [longemen3000/NativeNaNMath.jl#1]
div(1,0) is an error because Int64 does not handle Inf
Do you have something else in mind?

**Comment by longemen3000** [comment]
`div(x::Int, y:Int)::Int` works different than `x::Int/x::Int`. The first one has the explicit promise that, if the inputs are Ints, the output will be an Int. The second one uses the promotion machinery to give an appropriate type. 

I'm trying to not break promises about the returning type here, so in the case of `div(a, b)`, that is used because it returns integers, i don't see how an overload can improve the situation, it would just make a worse `div`. The same thing goes with any operation explicitly designed to work with integers

**Comment by longemen3000** [comment]
For NaN in integers, i see a NaN as an operation that allows to make division closed over reals. If a type cannot hold NaN, it will be promoted to a type it does. This promotion is handled by `zero(x)/zero(x)`, and for Int8, Int16, Int32, Int64 returns Float64. Complex and Duals work with this definition. Rationals need special handling because they define `/(::Rational, ::Rational)::Rational`, but you can in fact store the "Rational NaN" by doing `Base.unsafe_rational(0,0)`

**Comment by JeffreySarnoff** [comment]
oic
